# Generated by Django 3.0.5 on 2020-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('slots', models.CharField(choices=[('NONE', 'Select a slot'), ('1', 'Time 9:00 am to 11:00 am'), ('2', 'Time 11:00 am to 1:00 pm'), ('3', 'Time 3:00 pm to 5:00 pm')], max_length=100)),
                ('session_date', models.DateField(verbose_name='Session Date')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='username')),
                ('name', models.CharField(max_length=60)),
                ('isadmin', models.BooleanField(default=False)),
                ('sessions', models.ManyToManyField(blank=True, to='myapi.Session')),
            ],
        ),
    ]
